// Code generated by mygo; DO NOT EDIT.

package main

import "fmt"

// process keeps comments through transpilation.
func process() error {
	// call someFunc before printing
	result, err := someFunc() // original call
	if err != nil {
		return err
	}
	fmt.Println(result) // print result
	return nil
}

func someFunc() (string, error) {
	return "hello", nil
}
